<?php

/**
 * @file
 * Basic authentication login - install file.
 */

/**
 * Implements hook_uninstall().
 */
function restws_basic_auth_uninstall() {
  // Remove the username regex.
  config_set('restws.settings', 'restws_basic_auth_user_regex', NULL);
}

/**
 * Set the user name regex to accept all for backwards compatibility.
 */
function restws_basic_auth_update_1100() {
  // Set the username regex to accept all.
  config_set('restws.settings', 'restws_basic_auth_user_regex', '/.*/');
}
